stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t student-management-api .
    - docker tag student-management-api:latest your-registry/student-management-api:latest
    - docker push your-registry/student-management-api:latest

deploy:
  stage: deploy
  script:
    - kubectl apply -f kubernetes/configmap.yaml
    - kubectl apply -f kubernetes/secret.yaml
    - kubectl apply -f kubernetes/deployment.yaml
    - kubectl apply -f kubernetes/service.yaml
