apiVersion: v1
kind: ConfigMap
metadata:
  name: student-management-config
data:
  APP_ENV: "production"               
  LOG_LEVEL: "INFO"                   
  API_HOST: "0.0.0.0"                 
  API_PORT: "8000"                    
