apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-management-api
  template:
    metadata:
      labels:
        app: student-management-api
    spec:
      containers:
        - name: student-management-api
          image: your-registry/student-management-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: student-management-config
                  key: APP_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: student-management-config
                  key: LOG_LEVEL
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: student-management-config
                  key: API_HOST
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: student-management-config
                  key: API_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: student-management-secret
                  key: DATABASE_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: student-management-secret
                  key: API_KEY
