apiVersion: v1
kind: Service
metadata:
  name: student-management-api
spec:
  selector:
    app: student-management-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
